version: 2
registries:
  java-commons:
    type: maven-repository
    url: https://maven.pkg.github.com/xenoterracide/java-commons
    username: ${{ secrets.GITHUB_ACTOR }}
    token: ${{ secrets.GITHUB_TOKEN }}
updates:
  - package-ecosystem: "gradle"
    registries: ["java-commons"]
    directory: "/"
    commit-message:
      prefix: "feat(deps)"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "ci(deps)"
    schedule:
      interval: "weekly"
