version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    commit-message:
      prefix: "build(deps)"
    schedule:
      interval: "weekly"
      timezone: "US/Eastern"
    ignore:
      - dependency-name: "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(deps)"
