version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    commit-message:
      prefix: "feat(deps)"
    groups:
      gradle-updates:
        update-types:
          - "semver-major"
    schedule:
      interval: "weekly"
      timezone: "US/Eastern"
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "ci(deps)"
    schedule:
      interval: "weekly"
