# SPDX-FileCopyrightText: Copyright © 2024 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

schema: "module/**/*.graphqls"
documents: "module/**/*.graphql"
extensions:
  endpoints:
    default: http://localhost:8080/graphql
