# SPDX-FileCopyrightText: 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

server.port=9000
logging.level.root=info
logging.level.com.xenoterracide=debug
logging.level.org.springframework.security=trace
spring.application.name=auth-server
spring.main.banner-mode=off
spring.security.user.name=user
spring.security.user.password=pass
# match auth0
spring.security.oauth2.authorizationserver.endpoint.authorization-uri=/oauth/authorize
spring.security.oauth2.authorizationserver.endpoint.token-uri=/oauth/token

# public client for authorization code flow with PKCE
spring.security.oauth2.authorizationserver.client.public-client.registration.client-id=client
spring.security.oauth2.authorizationserver.client.public-client.registration.client-authentication-methods[0]=none
spring.security.oauth2.authorizationserver.client.public-client.registration.authorization-grant-types[0]=\
  authorization_code
spring.security.oauth2.authorizationserver.client.public-client.registration.redirect-uris[0]=http://localhost:3000
spring.security.oauth2.authorizationserver.client.public-client.registration.scopes[0]=openid
spring.security.oauth2.authorizationserver.client.public-client.registration.scopes[1]=profile
spring.security.oauth2.authorizationserver.client.public-client.registration.scopes[2]=email
spring.security.oauth2.authorizationserver.client.public-client.require-proof-key=true
spring.security.oauth2.authorizationserver.client.public-client.require-authorization-consent=false

# confidential client for client credentials flow
spring.security.oauth2.authorizationserver.client.confidential-client.registration.client-id=confidential
spring.security.oauth2.authorizationserver.client.confidential-client.registration.client-secret={noop}secret
spring.security.oauth2.authorizationserver.client.confidential-client.registration.client-authentication-methods[0]=\
  client_secret_basic
spring.security.oauth2.authorizationserver.client.confidential-client.registration.authorization-grant-types[0]=\
  client_credentials
spring.security.oauth2.authorizationserver.client.confidential-client.registration.scopes[0]=openid
spring.security.oauth2.authorizationserver.client.confidential-client.registration.scopes[1]=profile
spring.security.oauth2.authorizationserver.client.confidential-client.registration.scopes[2]=email
