# SPDX-FileCopyrightText: Copyright © 2025 - 2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

[versions]
ep = "2.+"
spring = "3.+"
plugin-convention = "0.16.+"
immutables = "2.+"

[libraries]
archunit-core = "com.tngtech.archunit:archunit:1.+"
archunit-junit-api = "com.tngtech.archunit:archunit-junit5-api:1.+"
assertj = "org.assertj:assertj-core:3.+"
equalsverifier = "nl.jqno.equalsverifier:equalsverifier:3.+"
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "ep" }
errorprone-nullaway = "com.uber.nullaway:nullaway:0.+"
hibernate-jpa-modelgen = { module = "org.hibernate.orm:hibernate-jpamodelgen", version.strictly = "6.+" }
immutables-annotate = { module = "org.immutables:annotate" }
immutables-annotations = { module = "org.immutables:value-annotations" }
immutables-bom = { module = "org.immutables:bom", version.ref = "immutables" }
immutables-builder = { module = "org.immutables:builder" }
immutables-core = { module = "org.immutables:value" }
jakarta-annotation = { module = "jakarta.annotation:jakarta.annotation-api" }
jakarta-bom = "jakarta.platform:jakarta.jakartaee-bom:10.+"
jakarta-cdi = { module = "jakarta.enterprise:jakarta.enterprise.cdi-api" }
jakarta-inject = { module = "jakarta.inject:jakarta.inject-api" }
jakarta-interceptor = { module = "jakarta.interceptor:jakarta.interceptor-api" }
jakarta-lang-model = { module = "jakarta.enterprise:jakarta.enterprise.lang-model" }
jakarta-transaction = { module = "jakarta.transaction:jakarta.transaction-api" }
java-tools = "com.xenoterracide:tools:0.+"
jboss-logging = { module = "org.jboss.logging:jboss-logging", version.strictly = "3.+" }
jmolecules-architecture-layered = { module = "org.jmolecules:jmolecules-layered-architecture" }
jmolecules-archunit = "org.jmolecules.integrations:jmolecules-archunit:1.+"
jmolecules-bom = "org.jmolecules:jmolecules-bom:2023.+"
jmolecules-ddd = { module = "org.jmolecules:jmolecules-ddd" }
jspecify = "org.jspecify:jspecify:1.+"
junit-bom = "org.junit:junit-bom:5.+"
junit-parameters = { module = "org.junit.jupiter:junit-jupiter-params" }
plantuml = "net.sourceforge.plantuml:plantuml:1.+"
plugin-convention-checkstyle = { module = "com.xenoterracide.gradle.convention:checkstyle", version.ref = "plugin-convention" }
plugin-convention-compile = { module = "com.xenoterracide.gradle.convention:compile", version.ref = "plugin-convention" }
plugin-convention-coverage = { module = "com.xenoterracide.gradle.convention:coverage", version.ref = "plugin-convention" }
plugin-convention-javadoc = { module = "com.xenoterracide.gradle.convention:javadoc", version.ref = "plugin-convention" }
plugin-convention-publish = { module = "com.xenoterracide.gradle.convention:publish", version.ref = "plugin-convention" }
plugin-convention-spotbugs = { module = "com.xenoterracide.gradle.convention:spotbugs", version.ref = "plugin-convention" }
plugin-convention-test = { module = "com.xenoterracide.gradle.convention:test", version.ref = "plugin-convention" }
plugin-dependency-analysis = "com.autonomousapps:dependency-analysis-gradle-plugin:3.+"
plugin-errorprone = "net.ltgt.gradle:gradle-errorprone-plugin:5.+"
spotbugs = "com.github.spotbugs:spotbugs:4.+"
spring-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring" }
spring-modulith-api = { module = "org.springframework.modulith:spring-modulith-api" }
spring-modulith-bom = { module = "org.springframework.modulith:spring-modulith-bom", version = "1.+" }
spring-modulith-core = { module = "org.springframework.modulith:spring-modulith-core" }
spring-modulith-test = { module = "org.springframework.modulith:spring-modulith-test" }
uuid-creator = "com.github.f4b6a3:uuid-creator:6.+"

[bundles]
compile = ["jakarta-annotation", "jspecify"]
immutables = ["immutables-annotations", "immutables-builder", "immutables-annotate"]
ep = ["errorprone-core", "errorprone-nullaway"]
jakarta-transaction = [
  "jakarta-transaction",
  "jakarta-cdi",
  "jakarta-lang-model",
  "jakarta-interceptor",
  "jakarta-inject",
]

[plugins]
dependency-analysis = { id = "com.autonomousapps.dependency-analysis" }
semver = { id = "com.xenoterracide.gradle.semver", version = "0.15.+" }
plantuml = { id = "io.gitlab.plunts.plantuml", version = "2.+" }
