# SPDX-FileCopyrightText: Copyright 2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

appender.0.type=Console
appender.0.name=CONSOLE
appender.0.layout.type=PatternLayout
appender.0.layout.pattern=%5p %-55.55class{.4} : %-120msg\tat %location%n%ex%n

logger.0.name=root
logger.0.level=INFO
logger.0.appenderRef.0.ref=CONSOLE

logger.1.name=com.xenoterracide
logger.1.level=DEBUG

logger.2.name=org.hibernate.SQL
logger.2.level=DEBUG

logger.3.name=com.arjuna.ats.jta
logger.3.level=TRACE
